[versions]
kotlin = "1.9.23"
loom = "1.6.+"

minecraft = "1.20.5"
fabric_loader = "0.15.10"
quilt_mappings = "0"

fabric_api = "0.97.5+1.20.5"
fabric_language_kotlin = "1.10.19+kotlin.1.9.23"
ktoml = "0.5.1"
yet_another_config_lib = "3.4.0+1.20.5-fabric"
mod_menu = "10.0.0-beta.1"
controlify = "2.0.0-beta.5+1.20.5-rc2"

settxi = "2.10.6"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }

fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }
fabric_language_kotlin = { module = "net.fabricmc:fabric-language-kotlin", version.ref = "fabric_language_kotlin" }
ktoml_core = { module = "com.akuleshov7:ktoml-core-jvm", version.ref = "ktoml" }
yet_another_config_lib = { module = "dev.isxander:yet-another-config-lib", version.ref = "yet_another_config_lib" }
mod_menu = { module = "com.terraformersmc:modmenu", version.ref = "mod_menu" }
controlify = { module = "dev.isxander:controlify", version.ref = "controlify" }
settxi_core = { module = "dev.isxander.settxi:settxi-core", version.ref = "settxi" }
settxi_serialization_kotlinx = { module = "dev.isxander.settxi:settxi-kotlinx-serialization", version.ref = "settxi" }

[bundles]
settxi = [
    "settxi_core",
    "settxi_serialization_kotlinx"
]

[plugins]
kotlin_jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin_plugin_serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

loom = { id = "fabric-loom", version.ref = "loom" }




